"use client";

export type DemoQuestion = { id: string; type: "multiple_choice" | "free_text" | "situational" | "structured_response"; prompt: string; options: string[]; required: boolean; order: number };
export type DemoTemplate = { id: string; name: string; description: string; timeLimitMinutes: number | null; attemptLimit: number; questions: DemoQuestion[]; createdAt: string; updatedAt: string; invitationCount: number };
export type DemoInvitation = { id: string; templateId: string; templateName: string; applicationId: string; candidateName: string; expiresAt: string | null; status: "pending" | "started" | "submitted" | "expired"; attemptId?: string; answers?: Record<string, unknown>; startedAt?: string; submittedAt?: string };
export type DemoReview = { attemptId: string; status: "pending" | "in_review" | "completed" | "disputed"; score: number | null; dimensionScores: Record<string, number>; notes: string | null; reviewedAt: string | null };

const key = "proofylink-assessments-demo-v1";
const reviewKey = "proofylink-assessment-reviews-demo-v1";
const defaultTemplate: DemoTemplate = { id: "demo-template-1", name: "Product thinking check-in", description: "A short, human-reviewed assessment for product roles.", timeLimitMinutes: 20, attemptLimit: 1, questions: [{ id: "demo-question-1", type: "multiple_choice", prompt: "Which signal would you validate first before changing a core workflow?", options: ["Anecdotal request", "Repeated user behavior", "Internal preference"], required: true, order: 0 }, { id: "demo-question-2", type: "free_text", prompt: "Describe how you would communicate an uncertain product decision.", options: [], required: true, order: 1 }], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), invitationCount: 1 };
const defaultInvitation: DemoInvitation = { id: "demo-invitation-1", templateId: defaultTemplate.id, templateName: defaultTemplate.name, applicationId: "demo-application-1", candidateName: "Nadia Pratama", expiresAt: null, status: "pending" };

type Store = { templates: DemoTemplate[]; invitations: DemoInvitation[] };
function read(): Store { try { const parsed = JSON.parse(localStorage.getItem(key) ?? "null") as Store | null; if (parsed?.templates && parsed.invitations) return parsed; } catch {} return { templates: [defaultTemplate], invitations: [defaultInvitation] }; }
function write(store: Store) { localStorage.setItem(key, JSON.stringify(store)); return store; }
export function listDemoTemplates() { return read().templates; }
export function getDemoTemplate(id: string) { return read().templates.find((item) => item.id === id) ?? null; }
export function saveDemoTemplate(input: Omit<DemoTemplate, "id" | "createdAt" | "updatedAt" | "invitationCount"> & { id?: string }) { const store = read(); const now = new Date().toISOString(); const existing = input.id ? store.templates.find((item) => item.id === input.id) : undefined; const template = { ...input, id: input.id ?? `demo-template-${crypto.randomUUID()}`, createdAt: existing?.createdAt ?? now, updatedAt: now, invitationCount: existing?.invitationCount ?? 0 }; write({ ...store, templates: existing ? store.templates.map((item) => item.id === template.id ? template : item) : [template, ...store.templates] }); return template; }
export function listDemoInvitations() { const store = read(); return store.invitations.map((invite) => ({ ...invite, templateName: store.templates.find((template) => template.id === invite.templateId)?.name ?? invite.templateName })); }
export function getDemoInvitation(id: string) { return listDemoInvitations().find((item) => item.id === id) ?? null; }
export function createDemoInvitation(template: DemoTemplate) { const store = read(); const invitation: DemoInvitation = { id: `demo-invitation-${crypto.randomUUID()}`, templateId: template.id, templateName: template.name, applicationId: "demo-application-1", candidateName: "Nadia Pratama", expiresAt: null, status: "pending" }; write({ templates: store.templates.map((item) => item.id === template.id ? { ...item, invitationCount: item.invitationCount + 1 } : item), invitations: [invitation, ...store.invitations] }); return invitation; }
export function startDemoAttempt(invitationId: string) { const store = read(); const invite = store.invitations.find((item) => item.id === invitationId); if (!invite) return null; const attemptId = invite.attemptId ?? `demo-attempt-${crypto.randomUUID()}`; const next = { ...invite, attemptId, status: "started" as const, startedAt: invite.startedAt ?? new Date().toISOString(), answers: invite.answers ?? {} }; write({ ...store, invitations: store.invitations.map((item) => item.id === invitationId ? next : item) }); return next; }
export function saveDemoAnswer(invitationId: string, questionId: string, response: unknown) { const store = read(); const invite = store.invitations.find((item) => item.id === invitationId); if (!invite || invite.status === "submitted") return invite ?? null; const next = { ...invite, answers: { ...(invite.answers ?? {}), [questionId]: response } }; write({ ...store, invitations: store.invitations.map((item) => item.id === invitationId ? next : item) }); return next; }
export function submitDemoAttempt(invitationId: string) { const store = read(); const invite = store.invitations.find((item) => item.id === invitationId); if (!invite) return null; const next = { ...invite, status: "submitted" as const, submittedAt: new Date().toISOString() }; write({ ...store, invitations: store.invitations.map((item) => item.id === invitationId ? next : item) }); return next; }
function readReviews(): DemoReview[] { try { return JSON.parse(localStorage.getItem(reviewKey) ?? "[]") as DemoReview[]; } catch { return []; } }
function writeReviews(reviews: DemoReview[]) { localStorage.setItem(reviewKey, JSON.stringify(reviews)); }
export function getDemoReview(attemptId: string) { return readReviews().find((review) => review.attemptId === attemptId) ?? null; }
export function saveDemoReview(review: DemoReview) { const reviews = readReviews(); writeReviews([review, ...reviews.filter((item) => item.attemptId !== review.attemptId)]); return review; }
