"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Package = { id: string; name: string; tokenAmount: number; priceMinor: number; currency: string };
type Payload = { packages?: Package[]; error?: string };
const money = (amount: number, currency: string) => new Intl.NumberFormat("id-ID", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount / 100);
export function BillingWorkspace() {
  const [packages, setPackages] = useState<Package[]>([]); const [balance, setBalance] = useState<number | null>(null); const [spendLimit, setSpendLimit] = useState<number | null>(null); const [purchases, setPurchases] = useState<Array<{ purchase: { status: string; tokenAmount: number; amountMinor: number; currency: string; createdAt: string }; package: string }>>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  useEffect(() => { Promise.all([fetch("/api/billing/packages"), fetch("/api/tokens"), fetch("/api/billing/account"), fetch("/api/billing/purchases")]).then(async ([a, b, c, d]) => { const p = await a.json() as Payload; const t = await b.json() as { token?: { balance: number }; error?: string }; const account = await c.json() as { account?: { spendLimit: number | null }; error?: string }; const history = await d.json() as { purchases?: typeof purchases; error?: string }; if (!a.ok || !b.ok || !c.ok || !d.ok) throw new Error(p.error || t.error || account.error || history.error || "Data billing belum tersedia."); setPackages(p.packages ?? []); setBalance(t.token?.balance ?? 0); setSpendLimit(account.account?.spendLimit ?? null); setPurchases(history.purchases ?? []); }).catch((e: Error) => setError(e.message)); }, []);
  async function checkout(id: string) { setBusy(id); setError(null); try { const response = await fetch("/api/billing/checkout", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": `ui-${id}` }, body: JSON.stringify({ packageId: id }) }); const result = await response.json() as { checkoutUrl?: string; error?: string }; if (!response.ok) throw new Error(result.error || "Checkout gagal."); if (result.checkoutUrl) window.location.assign(result.checkoutUrl); } catch (e) { setError(e instanceof Error ? e.message : "Checkout gagal."); } finally { setBusy(null); } }
  return <div className="container mx-auto max-w-6xl px-4 py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-widest text-primary">Recruiter commerce</p><h1 className="mt-2 text-3xl font-bold">Billing & tokens</h1><p className="mt-2 text-muted-foreground">Kelola saldo token organisasi dan pembelian.</p></div><div className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-900">Development mock checkout</div></div>{error && <div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{error}</div>}<div className="mt-8 grid gap-4 md:grid-cols-3"><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Token balance</p><p className="mt-2 font-mono text-4xl font-bold">{balance === null ? "..." : balance}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Spend limit</p><p className="mt-2 text-2xl font-bold">{spendLimit === null ? "Tidak dibatasi" : money(spendLimit, "IDR")}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Mode pembayaran</p><p className="mt-2 font-semibold">Mock, development only</p></CardContent></Card></div><section className="mt-8"><h2 className="text-xl font-bold">Token packages</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{packages.map((pkg) => <Card key={pkg.id} className="card-interactive"><CardHeader><CardTitle>{pkg.name}</CardTitle><p className="text-sm text-muted-foreground">{pkg.tokenAmount} tokens</p></CardHeader><CardContent><p className="text-2xl font-bold">{money(pkg.priceMinor, pkg.currency)}</p><Button className="mt-5 w-full" onClick={() => checkout(pkg.id)} disabled={busy === pkg.id}>{busy === pkg.id ? "Membuka checkout..." : "Beli paket"}</Button></CardContent></Card>)}</div></section><section className="mt-8"><h2 className="text-xl font-bold">Purchases</h2><div className="mt-4 overflow-x-auto rounded-2xl border bg-card">{purchases.length ? <table className="w-full min-w-[520px] text-left text-sm"><thead className="border-b bg-muted"><tr><th className="p-4">Package</th><th className="p-4">Tokens</th><th className="p-4">Status</th><th className="p-4">Date</th></tr></thead><tbody>{purchases.map((row) => <tr key={row.purchase.createdAt} className="border-b last:border-0"><td className="p-4">{row.package}</td><td className="p-4 font-mono">{row.purchase.tokenAmount}</td><td className="p-4">{row.purchase.status}</td><td className="p-4 text-muted-foreground">{new Date(row.purchase.createdAt).toLocaleDateString("id-ID")}</td></tr>)}</tbody></table> : <p className="p-6 text-sm text-muted-foreground">Belum ada pembelian.</p>}</div></section></div>;
}
