"use client";
import { Download, FileText, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { candidates } from "@/data/candidates";
import { useApp } from "@/providers/app-provider";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
export default function Shortlist() { const { shortlisted, scans, notes, saveNote, toggleShortlist, user } = useApp(); if (!user || user.role !== "recruiter") return <ProtectedRoute role="recruiter"><div /></ProtectedRoute>; const ids = [...new Set([...shortlisted, ...scans.map((scan) => scan.candidateId)])]; const list = candidates.filter((candidate) => ids.includes(candidate.id)); const exportCsv = () => { const rows = [["Name", "Role", "Location", "Experience", "Skills", "Availability", "Salary", "Notes"], ...list.map((candidate) => [candidate.name, candidate.role, candidate.location, String(candidate.experience), candidate.skills.join(" | "), candidate.availability, candidate.salary, notes[candidate.id] ?? ""])]; const blob = new Blob([rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "proofylink-shortlist.csv"; link.click(); URL.revokeObjectURL(url); toast.success("Shortlist exported"); }; return <div className="container mx-auto px-4 py-8"><div className="flex flex-col justify-between gap-4 border-b pb-7 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-widest text-[#7C3AED]">Your working set</p><h1 className="mt-2 text-3xl font-bold">Shortlist</h1><p className="mt-2 text-muted-foreground">Kandidat yang layak kamu kunjungi kembali.</p></div>{list.length > 0 && <Button variant="outline" onClick={exportCsv}><Download className="size-4" /> Export CSV</Button>}</div>{list.length ? <div className="mt-8 flex flex-col gap-4">{list.map((candidate) => <Card key={candidate.id}><CardContent className="grid gap-4 p-5 md:grid-cols-[1fr_1.4fr_auto] md:items-center"><div><p className="font-semibold">{candidate.name}</p><p className="text-sm text-muted-foreground">{candidate.role} · {candidate.location}</p></div><div className="relative"><FileText className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input defaultValue={notes[candidate.id] ?? ""} onBlur={(event) => { saveNote(candidate.id, event.target.value); toast.success("Note saved"); }} placeholder="Add a private note..." className="pl-9" /></div><Button variant="ghost" size="icon" aria-label={`Remove ${candidate.name}`} onClick={() => toggleShortlist(candidate.id)}><Trash2 className="size-4 text-muted-foreground" /></Button></CardContent></Card>)}</div> : <div className="mt-12 rounded-2xl border border-dashed bg-white p-12 text-center"><h2 className="text-xl font-bold">Your shortlist is empty</h2><p className="mt-2 text-muted-foreground">Simpan kandidat dari Search untuk membangun working set.</p><Button className="mt-5" asChild><a href="/search">Search talent</a></Button></div>}</div>; }
