"use client";
import { Download, FileText, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { candidates } from "@/data/candidates";
import { useApp } from "@/providers/app-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
export default function Shortlist() { const { shortlisted, scans, notes, saveNote, toggleShortlist } = useApp(); const ids = [...new Set([...shortlisted, ...scans.map((s) => s.candidateId)])]; const list = candidates.filter((c) => ids.includes(c.id)); const exportCsv = () => { const rows = [["Name","Role","Location","Experience","Skills","Availability","Salary","Notes"], ...list.map((c) => [c.name,c.role,c.location,String(c.experience),c.skills.join(" | "),c.availability,c.salary,notes[c.id] ?? ""])]; const blob = new Blob([rows.map((row) => row.map((cell) => `"${cell.replaceAll('"','""')}"`).join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "talent-network-shortlist.csv"; link.click(); URL.revokeObjectURL(url); toast.success("Shortlist exported"); }; return <div className="container mx-auto px-4 py-8"><div className="flex flex-col justify-between gap-4 border-b pb-7 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-widest text-primary">Your working set</p><h1 className="mt-2 text-3xl font-bold">Shortlist</h1><p className="mt-2 text-muted-foreground">Keep the people worth coming back to close.</p></div>{list.length > 0 && <Button variant="outline" onClick={exportCsv}><Download className="size-4" /> Export CSV</Button>}</div>{list.length ? <div className="mt-8 flex flex-col gap-4">{list.map((c) => <Card key={c.id}><CardContent className="grid gap-4 p-5 md:grid-cols-[1fr_1.4fr_auto] md:items-center"><div><p className="font-semibold">{c.name}</p><p className="text-sm text-muted-foreground">{c.role} · {c.location}</p></div><div className="relative"><FileText className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input defaultValue={notes[c.id] ?? ""} onBlur={(e) => { saveNote(c.id, e.target.value); toast.success("Note saved"); }} placeholder="Add a private note..." className="pl-9" /></div><Button variant="ghost" size="icon" onClick={() => toggleShortlist(c.id)} aria-label="Remove from shortlist"><Trash2 className="text-destructive" /></Button></CardContent></Card>)}</div> : <div className="py-24 text-center"><p className="text-lg font-semibold">Your shortlist is quiet.</p><p className="mt-2 text-sm text-muted-foreground">Save a profile or scan someone worth revisiting.</p><Button className="mt-5" asChild><a href="/search">Explore talent</a></Button></div>}</div>; }
