"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Props = { endpoint: string; kind: "recruiters" | "organizations" | "tokens" | "audit" };
export function AdminDataPage({ endpoint, kind }: Props) {
  const [data, setData] = useState<unknown>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [organizationId, setOrganizationId] = useState(""); const [amount, setAmount] = useState("1"); const [reason, setReason] = useState("");
  async function load() { try { const response = await fetch(endpoint, { cache: "no-store" }); const json = await response.json() as { error?: string }; if (!response.ok) throw new Error(json.error || "Data tidak tersedia."); setData(json); } catch (e) { setError(e instanceof Error ? e.message : "Data tidak tersedia."); } }
  // The endpoint is the component's request identity; reload when it changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [endpoint]);
  async function action(userId: string, actionName: "approve" | "reject") { setBusy(userId); const response = await fetch(`/api/admin/recruiters/${userId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, reason: actionName === "reject" ? reason : undefined }) }); if (!response.ok) setError(((await response.json()) as { error?: string }).error || "Update gagal."); else await load(); setBusy(null); }
  async function grant(event: FormEvent) { event.preventDefault(); setError(null); const response = await fetch("/api/admin/tokens", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, amount: Number(amount), type: "grant", reason, idempotencyKey: `admin-${organizationId}-${amount}-${reason}` }) }); if (!response.ok) setError(((await response.json()) as { error?: string }).error || "Grant gagal."); else { setOrganizationId(""); setReason(""); await load(); } }
  if (error) return <div className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-950" role="alert">{error}</div>;
  if (!data) return <div className="rounded-xl border bg-card p-6 text-sm text-muted-foreground" role="status">Memuat data...</div>;
  if (kind === "tokens") return <div className="grid gap-6"><form onSubmit={grant} className="rounded-2xl border bg-card p-6"><h2 className="font-semibold">Grant tokens</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Input aria-label="Organization ID" placeholder="Organization UUID" value={organizationId} onChange={(e) => setOrganizationId(e.target.value)} required /><Input aria-label="Amount" type="number" min="1" value={amount} onChange={(e) => setAmount(e.target.value)} required /><Input aria-label="Reason" placeholder="Reason" value={reason} onChange={(e) => setReason(e.target.value)} required /></div><Button className="mt-4">Grant tokens</Button></form><pre className="overflow-auto rounded-2xl border bg-card p-6 text-xs">{JSON.stringify(data, null, 2)}</pre></div>;
  if (kind === "recruiters") { const rows = (data as { recruiters: Array<{ user: { id: string; email: string; recruiterProvisioningStatus: string }; profile: { displayName: string | null } | null }> }).recruiters; return <div className="grid gap-4">{rows.length ? rows.map((row) => <div key={row.user.id} className="flex flex-col justify-between gap-4 rounded-2xl border bg-card p-5 sm:flex-row sm:items-center"><div><p className="font-semibold">{row.profile?.displayName || row.user.email}</p><p className="text-sm text-muted-foreground">{row.user.email} · {row.user.recruiterProvisioningStatus}</p></div><div className="flex gap-2"><Button size="sm" onClick={() => action(row.user.id, "approve")} disabled={busy === row.user.id}>Approve</Button><Button size="sm" variant="destructive" onClick={() => action(row.user.id, "reject")} disabled={busy === row.user.id}>Reject</Button></div></div>) : <p className="rounded-xl border bg-card p-6 text-sm text-muted-foreground">Belum ada recruiter.</p>}<Input aria-label="Rejection reason" placeholder="Alasan reject (wajib saat reject)" value={reason} onChange={(e) => setReason(e.target.value)} /></div>; }
   const key = kind === "organizations" ? "organizations" : "logs"; const rows = (data as Record<string, unknown>)[key];
   if (kind === "audit") {
     const logs = Array.isArray(rows) ? rows as Array<{ log?: { id: string; createdAt: string; action: string; entityType: string; entityId: string | null; organizationId: string | null; metadata: Record<string, unknown> }; actorEmail?: string | null }> : [];
     return logs.length ? <div className="grid gap-3">{logs.map((row) => { const log = row.log; if (!log) return null; return <article key={log.id} className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm"><time className="font-mono text-xs text-muted-foreground" dateTime={log.createdAt}>{new Date(log.createdAt).toLocaleString()}</time><span className="font-semibold">{log.action}</span><span className="text-muted-foreground">{log.entityType}{log.entityId ? ` · ${log.entityId}` : ""}</span></div><p className="mt-1 text-xs text-muted-foreground">Actor: {row.actorEmail ?? "System"}{log.organizationId ? ` · Organization: ${log.organizationId}` : ""}</p><pre className="mt-3 max-h-40 overflow-auto rounded-md bg-muted p-3 text-xs">{JSON.stringify(log.metadata ?? {}, null, 2)}</pre></article>; })}</div> : <p className="rounded-xl border bg-card p-6 text-sm text-muted-foreground">Belum ada data. Mode demo tidak menampilkan data palsu.</p>;
   }
   return Array.isArray(rows) && rows.length ? <div className="grid gap-3">{rows.map((row, index) => <pre key={index} className="overflow-auto rounded-xl border bg-card p-4 text-xs">{JSON.stringify(row, null, 2)}</pre>)}</div> : <p className="rounded-xl border bg-card p-6 text-sm text-muted-foreground">Belum ada data. Mode demo tidak menampilkan data palsu.</p>;
}
