import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { schema } from "@/db";
import { writeAuditLog } from "@/lib/audit";
import { currentUserOrError } from "@/lib/billing/access";

export async function PATCH(request: Request, { params }: { params: Promise<{ userId: string }> }) {
  const current = await currentUserOrError(); if ("error" in current) return NextResponse.json({ error: current.error }, { status: current.status }); if (current.user.role !== "admin") return NextResponse.json({ error: "Akses admin diperlukan." }, { status: 403 });
  const body = z.object({ action: z.enum(["approve", "reject"]), reason: z.string().trim().max(500).optional(), organizationId: z.string().uuid().optional(), organizationRole: z.enum(["owner", "admin", "recruiter", "viewer"]).optional() }).strict().safeParse(await request.json()); if (!body.success || (body.data.action === "reject" && !body.data.reason)) return NextResponse.json({ error: "Action recruiter tidak valid." }, { status: 400 });
   const { userId } = await params; const result = await current.db.transaction(async (tx) => { const [user] = await tx.update(schema.users).set({ recruiterProvisioningStatus: body.data.action === "approve" ? "active" : "rejected", updatedAt: new Date() }).where(eq(schema.users.id, userId)).returning(); if (!user || user.role !== "recruiter") return { error: "Recruiter tidak ditemukan.", status: 404 as const }; let membershipChanged = false; if (body.data.organizationId) { const [membership] = await tx.insert(schema.organizationMembers).values({ organizationId: body.data.organizationId, userId, role: body.data.organizationRole ?? "recruiter" }).onConflictDoUpdate({ target: [schema.organizationMembers.organizationId, schema.organizationMembers.userId], set: { role: body.data.organizationRole ?? "recruiter" } }).returning(); membershipChanged = Boolean(membership); await writeAuditLog({ db: tx, actorUserId: current.user.id, organizationId: body.data.organizationId, action: "organization.member.updated", entityType: "organization_member", entityId: membership?.id ?? null, metadata: { memberUserId: userId, role: body.data.organizationRole ?? "recruiter" } }); } await writeAuditLog({ db: tx, actorUserId: current.user.id, action: `admin.recruiter.${body.data.action}`, entityType: "user", entityId: user.id, metadata: { reason: body.data.reason ?? null, organizationId: body.data.organizationId ?? null, membershipChanged } }); return { user }; }); if ("error" in result) return NextResponse.json({ error: result.error }, { status: result.status }); return NextResponse.json({ user: result.user });
}
