"use client";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import type { CvProfile } from "@/types";
import {
  Check,
  RotateCcw,
} from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

interface ProfessionalSummaryModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  currentSummary?: string;
  cvProfile?: CvProfile | null;
  onApply: (newSummary: string) => void | Promise<void>;
}

interface SummaryFormState {
  totalExperience: string;
  coreCompetencies: string;
  industryExperience: string;
  toolsAndHardSkills: string;
  softSkills: string;
}

const INITIAL_FORM: SummaryFormState = {
  totalExperience: "",
  coreCompetencies: "",
  industryExperience: "",
  toolsAndHardSkills: "",
  softSkills: "",
};

function formatGeneratedSummary(form: SummaryFormState): string {
  const {
    totalExperience,
    coreCompetencies,
    industryExperience,
    toolsAndHardSkills,
    softSkills,
  } = form;

  const parts: string[] = [];

  // 1. Total Experience & Core Competencies
  if (totalExperience.trim() && coreCompetencies.trim()) {
    parts.push(
      `Memiliki pengalaman ${totalExperience.trim()} dengan kompetensi pada ${coreCompetencies.trim()}.`
    );
  } else if (totalExperience.trim()) {
    parts.push(`Memiliki pengalaman ${totalExperience.trim()}.`);
  } else if (coreCompetencies.trim()) {
    parts.push(`Memiliki fokus kompetensi pada ${coreCompetencies.trim()}.`);
  }

  // 2. Industry Experience, Tools, and Soft Skills
  const secondSentenceParts: string[] = [];

  if (industryExperience.trim()) {
    secondSentenceParts.push(`Berpengalaman pada industri ${industryExperience.trim()}`);
  }

  if (toolsAndHardSkills.trim()) {
    if (secondSentenceParts.length > 0) {
      secondSentenceParts.push(`menguasai ${toolsAndHardSkills.trim()}`);
    } else {
      secondSentenceParts.push(`Menguasai ${toolsAndHardSkills.trim()}`);
    }
  }

  if (softSkills.trim()) {
    if (secondSentenceParts.length > 0) {
      secondSentenceParts.push(
        `serta memiliki kemampuan ${softSkills.trim()} yang baik`
      );
    } else {
      secondSentenceParts.push(
        `Memiliki kemampuan ${softSkills.trim()} yang baik`
      );
    }
  }

  if (secondSentenceParts.length > 0) {
    parts.push(`${secondSentenceParts.join(", ")}.`);
  }

  return parts.join(" ").trim();
}

export function ProfessionalSummaryModal({
  open,
  onOpenChange,
  currentSummary = "",
  cvProfile,
  onApply,
}: ProfessionalSummaryModalProps) {
  const [form, setForm] = useState<SummaryFormState>(INITIAL_FORM);
  const [customText, setCustomText] = useState<string>("");
  const [isManualEdit, setIsManualEdit] = useState<boolean>(false);
  const [isApplying, setIsApplying] = useState<boolean>(false);

  // Auto-generate preview sentence based on 5 fields
  const autoGenerated = useMemo(() => formatGeneratedSummary(form), [form]);

  // Derived preview text
  const previewText = isManualEdit ? customText : (autoGenerated || currentSummary);

  const handleFieldChange = (field: keyof SummaryFormState, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    setIsManualEdit(false);
  };

  const handleToggleManualEdit = () => {
    if (!isManualEdit) {
      setCustomText(autoGenerated || currentSummary);
      setIsManualEdit(true);
    } else {
      setIsManualEdit(false);
    }
  };

  const handleAutoPopulate = () => {
    if (!cvProfile) {
      toast.info("Data profil CV belum tersedia untuk pengisian otomatis.");
      return;
    }

    const expCount = cvProfile.experience?.length || 0;
    const yearsText =
      expCount > 0
        ? `lebih dari ${expCount} tahun di bidang ${cvProfile.targetRole || cvProfile.headline || "Profesional"}`
        : `di bidang ${cvProfile.targetRole || cvProfile.headline || "Profesional"}`;

    const skills = (cvProfile.skills || []).slice(0, 4).join(", ");
    const tools = (cvProfile.tools || []).slice(0, 4).join(", ");
    const softSkills = (cvProfile.softSkills || []).slice(0, 3).join(", ");
    const industries = (cvProfile.industries || []).slice(0, 3).join(", ");

    setForm({
      totalExperience: yearsText,
      coreCompetencies: skills || "manajemen proyek dan analisis data",
      industryExperience: industries || "Teknologi dan Layanan Profesional",
      toolsAndHardSkills: tools || "aplikasi produktivitas dan sistem manajemen terkait",
      softSkills: softSkills || "komunikasi, kerja sama tim, dan pemecahan masalah",
    });

    setIsManualEdit(false);
    toast.success("Form berhasil diisi dari data profil & CV.");
  };

  const handleReset = () => {
    setForm(INITIAL_FORM);
    setCustomText("");
    setIsManualEdit(false);
  };

  const handleApply = async () => {
    const finalSummary = previewText.trim();
    if (!finalSummary) {
      toast.error("Silakan isi setidaknya satu bagian untuk membuat ringkasan.");
      return;
    }

    try {
      setIsApplying(true);
      await onApply(finalSummary);
      toast.success("Professional Summary berhasil diperbarui di profil dan CV.");
      onOpenChange(false);
    } catch {
      toast.error("Gagal menyimpan summary. Silakan coba lagi.");
    } finally {
      setIsApplying(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto rounded-lg p-4 sm:p-6">
        <DialogHeader className="gap-1 border-b pb-4 pr-10 sm:pr-12">
          <div className="flex items-center justify-between gap-4">
            <DialogTitle className="text-sm font-semibold text-foreground">
              Panduan summary profesional
            </DialogTitle>
            {cvProfile && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleAutoPopulate}
                className="hidden shrink-0 gap-1.5 rounded-md text-xs font-medium sm:inline-flex"
              >
                Isi dari data profil
              </Button>
            )}
          </div>
          <DialogDescription className="text-xs text-muted-foreground">
            Formula 5 bagian: pengalaman, kompetensi inti, industri, tools, dan soft skills.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-2">
          {/* 5 Input Guidance Pillars */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {/* 1. Total Experience */}
            <div className="space-y-1.5 sm:col-span-2">
              <label className="text-sm font-medium text-foreground">
                Total pengalaman
              </label>
              <input
                type="text"
                value={form.totalExperience}
                onChange={(e) => handleFieldChange("totalExperience", e.target.value)}
                placeholder="Contoh: lebih dari 2 tahun di bidang Human Capital"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:border-ring focus:outline-none focus:ring-[3px] focus:ring-ring/50"
              />
              <p className="text-xs text-muted-foreground">
                Lama pengalaman dan bidang utama.
              </p>
            </div>

            {/* 2. Core Competencies */}
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">
                Kompetensi inti
              </label>
              <input
                type="text"
                value={form.coreCompetencies}
                onChange={(e) => handleFieldChange("coreCompetencies", e.target.value)}
                placeholder="Contoh: Payroll, Recruitment"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:border-ring focus:outline-none focus:ring-[3px] focus:ring-ring/50"
              />
              <p className="text-xs text-muted-foreground">
                Spesialisasi yang paling dikuasai.
              </p>
            </div>

            {/* 3. Industry Experience */}
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">
                Latar industri
              </label>
              <input
                type="text"
                value={form.industryExperience}
                onChange={(e) => handleFieldChange("industryExperience", e.target.value)}
                placeholder="Contoh: Financial Technology"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:border-ring focus:outline-none focus:ring-[3px] focus:ring-ring/50"
              />
              <p className="text-xs text-muted-foreground">
                Sektor tempat pernah berkontribusi.
              </p>
            </div>

            {/* 4. Tools & Hard Skills */}
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">
                Tools dan hard skill
              </label>
              <input
                type="text"
                value={form.toolsAndHardSkills}
                onChange={(e) => handleFieldChange("toolsAndHardSkills", e.target.value)}
                placeholder="Contoh: Talenta HRIS, Google Workspace"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:border-ring focus:outline-none focus:ring-[3px] focus:ring-ring/50"
              />
              <p className="text-xs text-muted-foreground">
                Software atau metode teknis yang dikuasai.
              </p>
            </div>

            {/* 5. Soft Skills */}
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">
                Soft skills
              </label>
              <input
                type="text"
                value={form.softSkills}
                onChange={(e) => handleFieldChange("softSkills", e.target.value)}
                placeholder="Contoh: komunikasi dan public speaking"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:border-ring focus:outline-none focus:ring-[3px] focus:ring-ring/50"
              />
              <p className="text-xs text-muted-foreground">
                Gaya komunikasi dan kolaborasi.
              </p>
            </div>
          </div>

          {/* Live Preview Box */}
          <div className="space-y-2 rounded-md border bg-muted p-4">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-foreground">
                Pratinjau summary
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleToggleManualEdit}
                  className="text-xs text-muted-foreground hover:text-foreground hover:underline"
                >
                  {isManualEdit ? "Kembali ke otomatis" : "Edit manual"}
                </button>
              </div>
            </div>

            {isManualEdit ? (
              <textarea
                value={customText}
                onChange={(e) => setCustomText(e.target.value)}
                rows={4}
                className="w-full rounded-md border bg-background p-3 text-sm leading-relaxed text-foreground focus:border-ring focus:outline-none focus:ring-[3px] focus:ring-ring/50"
                placeholder="Tulis atau sesuaikan summary di sini..."
              />
            ) : (
              <div className="min-h-[72px] rounded-md bg-background p-3 text-sm leading-relaxed text-foreground shadow-xs">
                {previewText ? (
                  <span>{previewText}</span>
                ) : (
                  <span className="italic text-muted-foreground">
                    Isi poin di atas untuk melihat ringkasan otomatis...
                  </span>
                )}
              </div>
            )}
          </div>
        </div>

        <DialogFooter className="flex flex-col-reverse items-center justify-between gap-2 border-t pt-4 sm:flex-row">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={handleReset}
            className="text-xs text-muted-foreground hover:text-foreground"
          >
            <RotateCcw className="mr-1.5 h-4 w-4" />
            Reset
          </Button>

          <div className="flex w-full items-center justify-end gap-2 sm:w-auto">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              className="rounded-md"
            >
              Batal
            </Button>
            <Button
              type="button"
              onClick={handleApply}
              disabled={isApplying || !previewText.trim()}
              className="rounded-md"
            >
              <Check className="mr-1.5 h-4 w-4" />
              {isApplying ? "Menyimpan..." : "Terapkan"}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
