"use client";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import type { CvProfile } from "@/types";
import {
  Briefcase,
  Building2,
  Check,
  Layers,
  RotateCcw,
  Sparkles,
  UserCheck,
  Wrench,
} from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

interface ProfessionalSummaryModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  currentSummary?: string;
  cvProfile?: CvProfile | null;
  onApply: (newSummary: string) => void | Promise<void>;
}

interface SummaryFormState {
  totalExperience: string;
  coreCompetencies: string;
  industryExperience: string;
  toolsAndHardSkills: string;
  softSkills: string;
}

const INITIAL_FORM: SummaryFormState = {
  totalExperience: "",
  coreCompetencies: "",
  industryExperience: "",
  toolsAndHardSkills: "",
  softSkills: "",
};

function formatGeneratedSummary(form: SummaryFormState): string {
  const {
    totalExperience,
    coreCompetencies,
    industryExperience,
    toolsAndHardSkills,
    softSkills,
  } = form;

  const parts: string[] = [];

  // 1. Total Experience & Core Competencies
  if (totalExperience.trim() && coreCompetencies.trim()) {
    parts.push(
      `Memiliki pengalaman ${totalExperience.trim()} dengan kompetensi pada ${coreCompetencies.trim()}.`
    );
  } else if (totalExperience.trim()) {
    parts.push(`Memiliki pengalaman ${totalExperience.trim()}.`);
  } else if (coreCompetencies.trim()) {
    parts.push(`Memiliki fokus kompetensi pada ${coreCompetencies.trim()}.`);
  }

  // 2. Industry Experience, Tools, and Soft Skills
  const secondSentenceParts: string[] = [];

  if (industryExperience.trim()) {
    secondSentenceParts.push(`Berpengalaman pada industri ${industryExperience.trim()}`);
  }

  if (toolsAndHardSkills.trim()) {
    if (secondSentenceParts.length > 0) {
      secondSentenceParts.push(`menguasai ${toolsAndHardSkills.trim()}`);
    } else {
      secondSentenceParts.push(`Menguasai ${toolsAndHardSkills.trim()}`);
    }
  }

  if (softSkills.trim()) {
    if (secondSentenceParts.length > 0) {
      secondSentenceParts.push(
        `serta memiliki kemampuan ${softSkills.trim()} yang baik`
      );
    } else {
      secondSentenceParts.push(
        `Memiliki kemampuan ${softSkills.trim()} yang baik`
      );
    }
  }

  if (secondSentenceParts.length > 0) {
    parts.push(`${secondSentenceParts.join(", ")}.`);
  }

  return parts.join(" ").trim();
}

export function ProfessionalSummaryModal({
  open,
  onOpenChange,
  currentSummary = "",
  cvProfile,
  onApply,
}: ProfessionalSummaryModalProps) {
  const [form, setForm] = useState<SummaryFormState>(INITIAL_FORM);
  const [customText, setCustomText] = useState<string>("");
  const [isManualEdit, setIsManualEdit] = useState<boolean>(false);
  const [isApplying, setIsApplying] = useState<boolean>(false);

  // Auto-generate preview sentence based on 5 fields
  const autoGenerated = useMemo(() => formatGeneratedSummary(form), [form]);

  // Derived preview text
  const previewText = isManualEdit ? customText : (autoGenerated || currentSummary);

  const handleFieldChange = (field: keyof SummaryFormState, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    setIsManualEdit(false);
  };

  const handleToggleManualEdit = () => {
    if (!isManualEdit) {
      setCustomText(autoGenerated || currentSummary);
      setIsManualEdit(true);
    } else {
      setIsManualEdit(false);
    }
  };

  const handleAutoPopulate = () => {
    if (!cvProfile) {
      toast.info("Data profil CV belum tersedia untuk pengisian otomatis.");
      return;
    }

    const expCount = cvProfile.experience?.length || 0;
    const yearsText =
      expCount > 0
        ? `lebih dari ${expCount} tahun di bidang ${cvProfile.targetRole || cvProfile.headline || "Profesional"}`
        : `di bidang ${cvProfile.targetRole || cvProfile.headline || "Profesional"}`;

    const skills = (cvProfile.skills || []).slice(0, 4).join(", ");
    const tools = (cvProfile.tools || []).slice(0, 4).join(", ");
    const softSkills = (cvProfile.softSkills || []).slice(0, 3).join(", ");
    const industries = (cvProfile.industries || []).slice(0, 3).join(", ");

    setForm({
      totalExperience: yearsText,
      coreCompetencies: skills || "manajemen proyek dan analisis data",
      industryExperience: industries || "Teknologi dan Layanan Profesional",
      toolsAndHardSkills: tools || "aplikasi produktivitas dan sistem manajemen terkait",
      softSkills: softSkills || "komunikasi, kerja sama tim, dan pemecahan masalah",
    });

    setIsManualEdit(false);
    toast.success("Form berhasil diisi dari data profil & CV.");
  };

  const handleReset = () => {
    setForm(INITIAL_FORM);
    setCustomText("");
    setIsManualEdit(false);
  };

  const handleApply = async () => {
    const finalSummary = previewText.trim();
    if (!finalSummary) {
      toast.error("Silakan isi setidaknya satu bagian untuk membuat ringkasan.");
      return;
    }

    try {
      setIsApplying(true);
      await onApply(finalSummary);
      toast.success("Professional Summary berhasil diperbarui di profil dan CV.");
      onOpenChange(false);
    } catch {
      toast.error("Gagal menyimpan summary. Silakan coba lagi.");
    } finally {
      setIsApplying(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto p-6">
        <DialogHeader className="gap-1 border-b border-border pb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <Sparkles className="size-4" />
              </div>
              <DialogTitle className="text-xl font-bold text-foreground">
                Panduan Professional Summary
              </DialogTitle>
            </div>
            {cvProfile && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleAutoPopulate}
                className="hidden text-xs sm:inline-flex"
              >
                Isi dari Data Profil
              </Button>
            )}
          </div>
          <DialogDescription className="text-sm text-muted-foreground">
            Bantu rekruter memahami kualifikasimu dengan formula 5 pilar standar industri:
            Pengalaman, Kompetensi Inti, Industri, Tools, dan Kemampuan Interpersonal.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-2">
          {/* 5 Input Guidance Pillars */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {/* 1. Total Experience */}
            <div className="space-y-1.5 sm:col-span-2">
              <label className="flex items-center gap-1.5 text-xs font-semibold text-foreground">
                <Briefcase className="size-3.5 text-primary" />
                1. Total Pengalaman (Total Experience)
              </label>
              <input
                type="text"
                value={form.totalExperience}
                onChange={(e) => handleFieldChange("totalExperience", e.target.value)}
                placeholder="Contoh: lebih dari 2 tahun di bidang Human Capital"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground/60 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <p className="text-[11px] text-muted-foreground">
                Sebutkan lama pengalaman kerja dan bidang keahlian utama.
              </p>
            </div>

            {/* 2. Core Competencies */}
            <div className="space-y-1.5">
              <label className="flex items-center gap-1.5 text-xs font-semibold text-foreground">
                <Layers className="size-3.5 text-primary" />
                2. Kompetensi Inti (Core Competencies)
              </label>
              <input
                type="text"
                value={form.coreCompetencies}
                onChange={(e) => handleFieldChange("coreCompetencies", e.target.value)}
                placeholder="Contoh: Payroll, Recruitment, HR Administration"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground/60 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <p className="text-[11px] text-muted-foreground">
                Spesialisasi atau tanggung jawab inti yang paling kamu kuasai.
              </p>
            </div>

            {/* 3. Industry Experience */}
            <div className="space-y-1.5">
              <label className="flex items-center gap-1.5 text-xs font-semibold text-foreground">
                <Building2 className="size-3.5 text-primary" />
                3. Latar Industri (Industry Experience)
              </label>
              <input
                type="text"
                value={form.industryExperience}
                onChange={(e) => handleFieldChange("industryExperience", e.target.value)}
                placeholder="Contoh: Financial Technology dan Hospitality"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground/60 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <p className="text-[11px] text-muted-foreground">
                Sektor bisnis atau industri tempat kamu pernah berkontribusi.
              </p>
            </div>

            {/* 4. Tools & Hard Skills */}
            <div className="space-y-1.5">
              <label className="flex items-center gap-1.5 text-xs font-semibold text-foreground">
                <Wrench className="size-3.5 text-primary" />
                4. Tools dan Hard Skill
              </label>
              <input
                type="text"
                value={form.toolsAndHardSkills}
                onChange={(e) => handleFieldChange("toolsAndHardSkills", e.target.value)}
                placeholder="Contoh: Talenta HRIS, Google Workspace, Looker Studio"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground/60 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <p className="text-[11px] text-muted-foreground">
                Software, sistem, platform, atau metode teknis yang dikuasai.
              </p>
            </div>

            {/* 5. Soft Skills */}
            <div className="space-y-1.5">
              <label className="flex items-center gap-1.5 text-xs font-semibold text-foreground">
                <UserCheck className="size-3.5 text-primary" />
                5. Kemampuan Interpersonal (Soft Skills)
              </label>
              <input
                type="text"
                value={form.softSkills}
                onChange={(e) => handleFieldChange("softSkills", e.target.value)}
                placeholder="Contoh: komunikasi, networking, dan public speaking"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground/60 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <p className="text-[11px] text-muted-foreground">
                Sikap kerja, gaya komunikasi, atau keahlian kolaborasi tim.
              </p>
            </div>
          </div>

          {/* Live Preview Box */}
          <div className="space-y-2 rounded-lg border border-primary/20 bg-primary/5 p-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-primary">
                Pratinjau Kalimat Summary
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleToggleManualEdit}
                  className="text-xs text-primary hover:underline"
                >
                  {isManualEdit ? "Kembalikan ke Auto-Generate" : "Edit Teks Manual"}
                </button>
              </div>
            </div>

            {isManualEdit ? (
              <textarea
                value={customText}
                onChange={(e) => setCustomText(e.target.value)}
                rows={4}
                className="w-full rounded-md border border-primary/30 bg-background p-3 text-sm leading-relaxed text-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                placeholder="Tulis atau sesuaikan summary di sini..."
              />
            ) : (
              <div className="min-h-[72px] rounded-md bg-background/80 p-3 text-sm leading-relaxed text-foreground shadow-xs">
                {previewText ? (
                  <span>{previewText}</span>
                ) : (
                  <span className="italic text-muted-foreground">
                    Isi poin-poin di atas untuk melihat kalimat ringkasan profesional yang tersusun otomatis di sini...
                  </span>
                )}
              </div>
            )}
          </div>
        </div>

        <DialogFooter className="flex flex-col-reverse items-center justify-between gap-2 border-t border-border pt-4 sm:flex-row">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={handleReset}
            className="text-xs text-muted-foreground hover:text-foreground"
          >
            <RotateCcw className="mr-1.5 size-3.5" />
            Reset Form
          </Button>

          <div className="flex w-full items-center justify-end gap-2 sm:w-auto">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
            >
              Batal
            </Button>
            <Button
              type="button"
              onClick={handleApply}
              disabled={isApplying || !previewText.trim()}
              className="bg-primary text-primary-foreground hover:bg-primary/90"
            >
              <Check className="mr-1.5 size-4" />
              {isApplying ? "Menyimpan..." : "Terapkan ke Profil & CV"}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
