"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const types = ["identity", "email", "phone", "education", "employment", "certification", "portfolio"] as const;
const labels: Record<string, string> = { identity: "Identitas", email: "Email", phone: "Nomor telepon", education: "Pendidikan", employment: "Riwayat kerja", certification: "Sertifikasi", portfolio: "Portfolio" };
const states: Record<string, string> = { pending: "Menunggu review", verified: "Terverifikasi", expired: "Kedaluwarsa", revoked: "Dicabut", disputed: "Dalam dispute" };
type Verification = { id: string; type: string; status: string; disputeReason: string | null };

export function VerificationList() {
  const [rows, setRows] = useState<Verification[]>([]); const [error, setError] = useState<string | null>(null); const [type, setType] = useState<typeof types[number]>("identity"); const [busy, setBusy] = useState(false);
  async function load() { try { const response = await fetch("/api/verifications", { cache: "no-store" }); const body = await response.json() as { verifications?: Verification[]; error?: string }; if (!response.ok) throw new Error(body.error || "Data verifikasi belum tersedia."); setRows(body.verifications ?? []); } catch (e) { setError(e instanceof Error ? e.message : "Data verifikasi belum tersedia."); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function requestVerification() { setBusy(true); setError(null); const response = await fetch("/api/verifications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type }) }); if (!response.ok) setError(((await response.json()) as { error?: string }).error || "Permintaan gagal."); else await load(); setBusy(false); }
  async function dispute(id: string) { const reason = window.prompt("Jelaskan alasan dispute (minimal 10 karakter):", "Bukti perlu ditinjau ulang."); if (!reason) return; setBusy(true); const response = await fetch(`/api/verifications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "disputed", disputeReason: reason }) }); if (!response.ok) setError(((await response.json()) as { error?: string }).error || "Dispute gagal."); else await load(); setBusy(false); }
  return <div className="grid gap-6">{error && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950" role="alert">{error}</div>}<Card><CardHeader><CardTitle>Ajukan pemeriksaan</CardTitle><p className="text-sm text-muted-foreground">Pilih satu jenis bukti. Status akan berubah setelah review manual.</p></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row"><select aria-label="Jenis verifikasi" className="field" value={type} onChange={(event) => setType(event.target.value as typeof type)}>{types.map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select><Button onClick={() => void requestVerification()} disabled={busy}>{busy ? "Mengirim..." : "Ajukan"}</Button></CardContent></Card><div className="grid gap-3">{types.map((item) => { const row = rows.find((entry) => entry.type === item); const canDispute = row && ["verified", "expired", "revoked"].includes(row.status); return <Card key={item}><CardContent className="flex flex-col justify-between gap-3 p-5 sm:flex-row sm:items-center"><div><p className="font-semibold">{labels[item]}</p><p className="mt-1 text-sm text-muted-foreground">{row ? states[row.status] || row.status : "Belum diajukan"}</p></div><div className="flex items-center gap-2"><span className="rounded-full border px-3 py-1 text-xs font-semibold">{row ? states[row.status] || row.status : "Belum ada status"}</span>{canDispute && <Button size="sm" variant="outline" onClick={() => void dispute(row.id)} disabled={busy}>Ajukan dispute</Button>}</div></CardContent></Card>; })}</div></div>;
}
