import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { schema } from "@/db";
import { writeAuditLog } from "@/lib/audit";
import { currentUserOrError } from "@/lib/billing/access";

const grantSchema = z.object({ organizationId: z.string().uuid(), amount: z.number().int().positive(), type: z.enum(["grant", "refund"]), reason: z.string().trim().min(1).max(500), idempotencyKey: z.string().trim().min(8).max(200) }).strict();
export async function GET() { try { const current = await currentUserOrError(); if ("error" in current) return NextResponse.json({ error: current.error }, { status: current.status }); if (current.user.role !== "admin") return NextResponse.json({ error: "Akses admin diperlukan." }, { status: 403 }); const accounts = await current.db.select({ account: schema.tokenAccounts, organization: schema.organizations.name }).from(schema.tokenAccounts).innerJoin(schema.organizations, eq(schema.organizations.id, schema.tokenAccounts.organizationId)); return NextResponse.json({ accounts }); } catch { return NextResponse.json({ error: "Token accounts belum tersedia." }, { status: 503 }); } }
export async function POST(request: Request) { try { const current = await currentUserOrError(); if ("error" in current) return NextResponse.json({ error: current.error }, { status: current.status }); if (current.user.role !== "admin") return NextResponse.json({ error: "Akses admin diperlukan." }, { status: 403 }); const parsed = grantSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Grant token tidak valid.", details: parsed.error.flatten() }, { status: 400 }); const [account] = await current.db.insert(schema.tokenAccounts).values({ organizationId: parsed.data.organizationId }).onConflictDoUpdate({ target: schema.tokenAccounts.organizationId, set: { updatedAt: new Date() } }).returning(); const signedAmount = parsed.data.type === "grant" ? parsed.data.amount : -parsed.data.amount; if (signedAmount < 0 && account.balance < parsed.data.amount) return NextResponse.json({ error: "Saldo token tidak cukup untuk refund." }, { status: 409 }); const [entry] = await current.db.insert(schema.tokenLedgerEntries).values({ tokenAccountId: account.id, type: parsed.data.type, amount: parsed.data.amount, idempotencyKey: `admin:${parsed.data.idempotencyKey}`, metadata: { reason: parsed.data.reason, actorUserId: current.user.id } }).onConflictDoNothing({ target: schema.tokenLedgerEntries.idempotencyKey }).returning(); if (entry) await current.db.update(schema.tokenAccounts).set({ balance: account.balance + signedAmount, updatedAt: new Date() }).where(eq(schema.tokenAccounts.id, account.id)); await writeAuditLog({ db: current.db, actorUserId: current.user.id, organizationId: parsed.data.organizationId, action: `admin.tokens.${parsed.data.type}`, entityType: "token_account", entityId: account.id, metadata: { amount: parsed.data.amount, reason: parsed.data.reason, idempotencyKey: parsed.data.idempotencyKey } }); return NextResponse.json({ entry: entry ?? { idempotent: true }, balance: account.balance + (entry ? signedAmount : 0) }, { status: entry ? 201 : 200 }); } catch { return NextResponse.json({ error: "Operasi token gagal." }, { status: 503 }); } }
